Repository tobbify-team/tobbify, pull requests merged in 2024-12, with the labels that each got.

#13 add album covers to the listen music page
  app/database.py
  app/music_page.py
  requirements.txt
Labels: backend, miscellaneous

#15 sarki sozu gosterme eklendi
  app/database.py
  app/home_page.py
  app/recommendation.py
Labels: backend, miscellaneous

#16 gereksiz commentler silindi
  app/database.py
  app/home_page.py
  app/recommendation.py
  app/subscription.py
Labels: backend, miscellaneous

#18 edited lyrics box
  app/home_page.py
  app/login_page.py
  app/main.py
  app/playlist_page.py
  app/signup_page.py
  app/subscription.py
Labels: backend, miscellaneous

#19 data visualization add 4 graphs
  app/graphs.py
  app/home_page.py
  app/main.py
  requirements.txt
Labels: backend, miscellaneous

#20 added README.md
  README.md
  diagrams/EER.png
Labels: documentation, miscellaneous

#22 add index to db
  db/index.sql
Labels: miscellaneous, database
